[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std.workspace = true
faster-hex.workspace = true
molecule.workspace = true

[features]
default = []
distribution = []
proof = []
vault = []

[build-dependencies]
molecule-codegen.workspace = true
